// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvnE2-Rlzxs-kF_l0Am1mvxS0X-QDYPBk',
    appId: '1:169513250146:web:dfc8bf74d78ffb4731503b',
    messagingSenderId: '169513250146',
    projectId: 'countdown-app-20249',
    authDomain: 'countdown-app-20249.firebaseapp.com',
    storageBucket: 'countdown-app-20249.appspot.com',
    measurementId: 'G-NY5JEQ7M12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmct7POC6RgFzCWHhGSHsSLcsffOqXZQA',
    appId: '1:169513250146:android:ab7e93cbf738701a31503b',
    messagingSenderId: '169513250146',
    projectId: 'countdown-app-20249',
    storageBucket: 'countdown-app-20249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKK9A6Zb0skkvO02lBeggp7pw75BRLtI',
    appId: '1:169513250146:ios:97aa7afa5784fb5831503b',
    messagingSenderId: '169513250146',
    projectId: 'countdown-app-20249',
    storageBucket: 'countdown-app-20249.appspot.com',
    iosBundleId: 'com.example.countdownApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfKK9A6Zb0skkvO02lBeggp7pw75BRLtI',
    appId: '1:169513250146:ios:2bc5986f4c28e05e31503b',
    messagingSenderId: '169513250146',
    projectId: 'countdown-app-20249',
    storageBucket: 'countdown-app-20249.appspot.com',
    iosBundleId: 'com.example.countdownApp.RunnerTests',
  );
}
